name: ko-build

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install ko
        run: go install github.com/google/ko@latest

      - name: Build and push with ko
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          ko build --platform=linux/amd64,linux/arm64 --tags=${SHORT_SHA} .
